#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 03, 2022 11:38:59 PM +03  platform: Windows NT

import random
import time as t
import sys,sqlite3
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

db = sqlite3.connect("C:\\Users\\user\\PycharmProjects\\DatabaseProject\\DBFinal.db") #Connecting The DB to the python
cr = db.cursor() #editor line
root = tk.Tk()
current_window = None
EmPloyId = None
top = root
_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = '#d9d9d9' # X11 color: 'gray85'
_ana1color = '#d9d9d9' # X11 color: 'gray85'
_ana2color = '#ececec' # Closest X11 color: 'gray92'
#___________________________________
top.geometry("700x600+679+123")
top.minsize(120, 1)
top.maxsize(1924, 1061)
top.resizable(1,  1)
top.title("KU Airport Mangment System (Admin)")
top.configure(background="#d9d9d9")
#___________________________________
def main():
    def Egal ():
        global EmPloyId
        cr.execute(f"SELECT Salary,Lname,JobType,Fname,Age,AirPortName,EmployeeID,Sex,EPhone FROM Employee WHERE EmployeeID={EmPloyId};")
        EmInfo = cr.fetchall() #Fetching Data from the Date Base
        print(EmInfo)
        EmployeeInterface(EmInfo)
    #___________________________________
    def Destroy():
        global current_window
        if current_window is not None:
            current_window.destroy()
        else:
            pass
#___________________________________
    #destroy current window and return empty window
    def replace_window():
        global current_window
        if current_window is not None:
            current_window.destroy()
        current_window = tk.Toplevel(top)
        return current_window
    #___________________________________
    # this messege shown when login failed
    def LoginFailMessage():
        window = tk.Toplevel(top)
        window.geometry("700x600+679+123")
        label0 = tk.Label(window, text="EmployeeID or Password is wrong" )
        label0.configure(background="red")
        label0.configure(font="-family {Segoe UI} -size 16 -weight bold -slant italic")
        label0.pack()
    #___________________________________
    #book and cancel ticket to passenger
    pasportNUM = None
    def Book_and_Cansel(firname=None,secname=None,Agee0=None,passnum0=None):
        window = replace_window()
        window.geometry("700x600+679+123")
        top = window
        Label1 = tk.Label(top)
        Label1.place(relx=0.0, rely=0.0, height=58, width=700)
        Label1.configure(background="#70bbd1")
        Label1.configure(compound='left')
        Label1.configure(disabledforeground="#a3a3a3")
        Label1.configure(font="-family {Segoe UI} -size 24 -weight bold -slant italic")
        Label1.configure(foreground="#000000")

        Label1.configure(relief="solid")

        Label1.configure(text='''KU Airport Mangment System (Admin)''')

        Label2 = tk.Label(top)

        Label2.place(relx=0.471, rely=0.117, height=54, width=54)

        Label2.configure(anchor='w')

        Label2.configure(background="#d9d9d9")

        Label2.configure(compound='left')

        Label2.configure(disabledforeground="#a3a3a3")

        Label2.configure(foreground="#000000")

        photo_location = "./ezgif-5-4a4aa8b9f3.gif"

        global _img0

        _img0 = tk.PhotoImage(file=photo_location)

        Label2.configure(image=_img0)

        Label3 = tk.Label(top)

        Label3.place(relx=0.014, rely=0.217, height=31, width=686)

        Label3.configure(background="#a6a79a")

        Label3.configure(compound='left')

        Label3.configure(disabledforeground="#a3a3a3")

        Label3.configure(font="-family {Segoe UI} -size 14 -weight bold -slant italic -underline 1")

        Label3.configure(foreground="#000000")

        Label3.configure(relief="solid")

        Label3.configure(text='''Welcome To The Admin ( Book/Cancel Ticket )''')

        Label5_2 = tk.Label(top)

        Label5_2.place(relx=0.529, rely=0.4, height=31, width=106)

        Label5_2.configure(activebackground="#f9f9f9")

        Label5_2.configure(activeforeground="black")

        Label5_2.configure(background="#70bbd1")

        Label5_2.configure(compound='left')

        Label5_2.configure(disabledforeground="#a3a3a3")

        Label5_2.configure(foreground="#000000")

        Label5_2.configure(highlightbackground="#d9d9d9")

        Label5_2.configure(highlightcolor="black")

        Label5_2.configure(relief="solid")

        Label5_2.configure(text='''Passport Number''')

        Label5_2_1 = tk.Label(top)

        Label5_2_1.place(relx=0.043, rely=0.4, height=31, width=96)

        Label5_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1.configure(activeforeground="black")

        Label5_2_1.configure(background="#70bbd1")

        Label5_2_1.configure(compound='left')

        Label5_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1.configure(foreground="#000000")

        Label5_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1.configure(highlightcolor="black")

        Label5_2_1.configure(relief="solid")

        Label5_2_1.configure(text='''First Name''')

        Label5_2_1_1 = tk.Label(top)

        Label5_2_1_1.place(relx=0.043, rely=0.467, height=31, width=96)

        Label5_2_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_1.configure(activeforeground="black")

        Label5_2_1_1.configure(background="#70bbd1")

        Label5_2_1_1.configure(compound='left')

        Label5_2_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_1.configure(foreground="#000000")

        Label5_2_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_1.configure(highlightcolor="black")

        Label5_2_1_1.configure(relief="solid")

        Label5_2_1_1.configure(text='''Last Name''')


        Label5_2_1_2 = tk.Label(top)

        Label5_2_1_2.place(relx=1.114, rely=0.183, height=31, width=206)

        Label5_2_1_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2.configure(activeforeground="black")

        Label5_2_1_2.configure(background="#488184")

        Label5_2_1_2.configure(compound='left')

        Label5_2_1_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2.configure(foreground="#000000")

        Label5_2_1_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2.configure(highlightcolor="black")

        Label5_2_1_2.configure(relief="solid")

        Label5_2_1_2.configure(text='''First Name''')

        Label5_2_1_2_2 = tk.Label(top)

        Label5_2_1_2_2.place(relx=0.2, rely=0.467, height=31, width=206)

        Label5_2_1_2_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2.configure(activeforeground="black")

        Label5_2_1_2_2.configure(background="#dcf86b")

        Label5_2_1_2_2.configure(compound='left')

        Label5_2_1_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2.configure(foreground="#000000")

        Label5_2_1_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2.configure(highlightcolor="black")

        Label5_2_1_2_2.configure(relief="solid")

        Label5_2_1_2_2.configure(text=secname)  #passenger secondname

        Label5_2_1_2_2_1 = tk.Label(top)

        Label5_2_1_2_2_1.place(relx=0.686, rely=0.4, height=31, width=206)

        Label5_2_1_2_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2_1.configure(activeforeground="black")

        Label5_2_1_2_2_1.configure(background="#dcf86b")

        Label5_2_1_2_2_1.configure(compound='left')

        Label5_2_1_2_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2_1.configure(foreground="#000000")

        Label5_2_1_2_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2_1.configure(highlightcolor="black")

        Label5_2_1_2_2_1.configure(relief="solid")

        Label5_2_1_2_2_1.configure(text=passnum0) #passeneger's passportnumber


        Label5_2_1_2_1_1 = tk.Label(top)

        Label5_2_1_2_1_1.place(relx=1.029, rely=0.183, height=31, width=206)

        Label5_2_1_2_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1_1.configure(activeforeground="black")

        Label5_2_1_2_1_1.configure(background="#2f5355")

        Label5_2_1_2_1_1.configure(compound='left')

        Label5_2_1_2_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1_1.configure(foreground="#000000")

        Label5_2_1_2_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1_1.configure(highlightcolor="black")

        Label5_2_1_2_1_1.configure(relief="solid")

        Label5_2_1_2_1_1.configure(text='''First Name''')


        Label5_2_1_2_1_2 = tk.Label(top)

        Label5_2_1_2_1_2.place(relx=0.2, rely=0.4, height=31, width=206)

        Label5_2_1_2_1_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1_2.configure(activeforeground="black")

        Label5_2_1_2_1_2.configure(background="#dcf86b")

        Label5_2_1_2_1_2.configure(compound='left')

        Label5_2_1_2_1_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1_2.configure(foreground="#000000")

        Label5_2_1_2_1_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1_2.configure(highlightcolor="black")

        Label5_2_1_2_1_2.configure(relief="solid")

        Label5_2_1_2_1_2.configure(text=firname) #Passenger's firstname


        Button1_1_1 = tk.Button(top)

        Button1_1_1.place(relx=0.243, rely=1.567, height=44, width=77)

        Button1_1_1.configure(activebackground="#ececec")

        Button1_1_1.configure(activeforeground="#000000")

        Button1_1_1.configure(background="#970004")

        Button1_1_1.configure(compound='left')

        Button1_1_1.configure(cursor="fleur")

        Button1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1.configure(foreground="#000000")

        Button1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1.configure(highlightcolor="black")

        Button1_1_1.configure(pady="0")

        Button1_1_1.configure(relief="solid")

        Button1_1_1.configure(text='''Sign Out''')
        Button1_1_1.configure(command=Destroy) #close the windom

        Entry1 = tk.Entry(top)

        Entry1.place(relx=0.4, rely=0.3, height=31, relwidth=0.249)

        Entry1.configure(background="white")

        Entry1.configure(disabledforeground="#a3a3a3")

        Entry1.configure(font="TkFixedFont")

        Entry1.configure(foreground="#000000")

        Entry1.configure(insertbackground="black")

        Label5_2_1_3 = tk.Label(top)

        Label5_2_1_3.place(relx=0.114, rely=0.3, height=31, width=187)

        Label5_2_1_3.configure(activebackground="#f9f9f9")

        Label5_2_1_3.configure(activeforeground="black")

        Label5_2_1_3.configure(background="#70bbd1")

        Label5_2_1_3.configure(compound='left')

        Label5_2_1_3.configure(disabledforeground="#a3a3a3")

        Label5_2_1_3.configure(foreground="#000000")

        Label5_2_1_3.configure(highlightbackground="#d9d9d9")

        Label5_2_1_3.configure(highlightcolor="black")

        Label5_2_1_3.configure(relief="solid")

        Label5_2_1_3.configure(text='''Enter The Passport Number''')
        #Get the passenger's info from the DB
        def GetINPUT():
            global pasportNO
            pasportNO = Entry1.get() #gets the passport's number
            try:
                cr.execute("SELECT PassportNumber FROM Passenger")
                BList = [] #appends all passport number of the passengers
                for passp in cr.fetchall():
                    BList.append(passp[0])
                if str(pasportNO) in BList: #if the passport number exist in the array it will fetch all passenge's info
                    cr.execute(f"SELECT Fname,Lname,Age,PassportNumber FROM Passenger WHERE PassportNumber={pasportNO};")
                    PDAta = cr.fetchall()[0] #feches all the passenger's info in array ex:('mohammad', 'khaled', 1999, '1234567')
                    Book_and_Cansel(str(PDAta[0]),str(PDAta[1]),str(int(t.strftime("%Y"))-int(PDAta[2])),str(PDAta[3])) #fetching the passenger's info from the array list
                else:
                    pasportNO = None #no passport number or wrong
                    Book_and_Cansel(None,None,None,None)
            except:
                pasportNO = None
                Book_and_Cansel(None,None,None,None)

        Button1_1_1_1_1 = tk.Button(top)

        Button1_1_1_1_1.place(relx=0.657, rely=0.3, height=31, width=77)

        Button1_1_1_1_1.configure(activebackground="#ececec")

        Button1_1_1_1_1.configure(activeforeground="#000000")

        Button1_1_1_1_1.configure(background="#70bbd1")

        Button1_1_1_1_1.configure(compound='left')

        Button1_1_1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1.configure(foreground="#000000")

        Button1_1_1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1.configure(highlightcolor="black")

        Button1_1_1_1_1.configure(pady="0")

        Button1_1_1_1_1.configure(relief="solid")

        Button1_1_1_1_1.configure(text='''Search''')
        Button1_1_1_1_1.configure(command=GetINPUT) #after pressing search button to display passenger's info if passport number exit's and is the one in the entry


        Label5_2_1_1_1 = tk.Label(top)

        Label5_2_1_1_1.place(relx=0.529, rely=0.467, height=31, width=106)

        Label5_2_1_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_1_1.configure(activeforeground="black")

        Label5_2_1_1_1.configure(background="#70bbd1")

        Label5_2_1_1_1.configure(compound='left')

        Label5_2_1_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_1_1.configure(foreground="#000000")

        Label5_2_1_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_1_1.configure(highlightcolor="black")

        Label5_2_1_1_1.configure(relief="solid")

        Label5_2_1_1_1.configure(text='''Age''')



        Label5_2_1_2_2_2 = tk.Label(top)

        Label5_2_1_2_2_2.place(relx=0.686, rely=0.467, height=31, width=206)

        Label5_2_1_2_2_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2_2.configure(activeforeground="black")

        Label5_2_1_2_2_2.configure(background="#dcf86b")

        Label5_2_1_2_2_2.configure(compound='left')

        Label5_2_1_2_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2_2.configure(foreground="#000000")

        Label5_2_1_2_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2_2.configure(highlightcolor="black")

        Label5_2_1_2_2_2.configure(relief="solid")

        Label5_2_1_2_2_2.configure(text=Agee0)

        Button1_1_1_1_1_1 = tk.Button(top)

        Button1_1_1_1_1_1.place(relx=0.486, rely=0.933, height=31, width=97)


        Button1_1_1_1_1_1.configure(activebackground="#ececec")

        Button1_1_1_1_1_1.configure(activeforeground="#000000")

        Button1_1_1_1_1_1.configure(background="#970004")

        Button1_1_1_1_1_1.configure(compound='left')

        Button1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1_1.configure(foreground="#000000")

        Button1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1_1.configure(highlightcolor="black")

        Button1_1_1_1_1_1.configure(pady="0")

        Button1_1_1_1_1_1.configure(relief="solid")

        Button1_1_1_1_1_1.configure(text='''Sign Out''')

        Button1_1_1_1_1_1.configure(command=Destroy) #close the window


        menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)

        top.configure(menu = menubar)


        Button1_1_1_1_1_1_1 = tk.Button(top)

        Button1_1_1_1_1_1_1.place(relx=0.343, rely=0.933, height=31

                , width=97)

        Button1_1_1_1_1_1_1.configure(activebackground="#ececec")

        Button1_1_1_1_1_1_1.configure(activeforeground="#000000")

        Button1_1_1_1_1_1_1.configure(background="#70bbd1")

        Button1_1_1_1_1_1_1.configure(compound='left')

        Button1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1_1_1.configure(foreground="#000000")

        Button1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1_1_1.configure(highlightcolor="black")

        Button1_1_1_1_1_1_1.configure(pady="0")

        Button1_1_1_1_1_1_1.configure(relief="solid")

        Button1_1_1_1_1_1_1.configure(text='''Main Menu''')

        Button1_1_1_1_1_1_1.configure(command=Egal)

        Frame1 = tk.Frame(top)

        Frame1.place(relx=0.014, rely=0.55, relheight=0.375, relwidth=0.479)

        Frame1.configure(relief='groove')

        Frame1.configure(borderwidth="2")

        Frame1.configure(relief="groove")

        Frame1.configure(background="#d9d9d9")


        Label5_2_1_4 = tk.Label(Frame1)

        Label5_2_1_4.place(relx=0.0, rely=0.0, height=31, width=336)

        Label5_2_1_4.configure(activebackground="#f9f9f9")

        Label5_2_1_4.configure(activeforeground="black")

        Label5_2_1_4.configure(background="#70bbd1")

        Label5_2_1_4.configure(compound='left')

        Label5_2_1_4.configure(disabledforeground="#a3a3a3")

        Label5_2_1_4.configure(foreground="#000000")

        Label5_2_1_4.configure(highlightbackground="#d9d9d9")

        Label5_2_1_4.configure(highlightcolor="black")

        Label5_2_1_4.configure(relief="solid")

        Label5_2_1_4.configure(text='''Cancel A Ticket''')


        Label5_2_1_3_1 = tk.Label(Frame1)

        Label5_2_1_3_1.place(relx=0.03, rely=0.178, height=31, width=107)

        Label5_2_1_3_1.configure(activebackground="#f9f9f9")

        Label5_2_1_3_1.configure(activeforeground="black")

        Label5_2_1_3_1.configure(background="#70bbd1")

        Label5_2_1_3_1.configure(compound='left')

        Label5_2_1_3_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_3_1.configure(foreground="#000000")

        Label5_2_1_3_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_3_1.configure(highlightcolor="black")

        Label5_2_1_3_1.configure(relief="solid")

        Label5_2_1_3_1.configure(text='''Enter Flight Code''')


        Entry1_1 = tk.Entry(Frame1)

        Entry1_1.place(relx=0.358, rely=0.178, height=31, relwidth=0.43)

        Entry1_1.configure(background="white")

        Entry1_1.configure(disabledforeground="#a3a3a3")

        Entry1_1.configure(font="TkFixedFont")

        Entry1_1.configure(foreground="#000000")

        Entry1_1.configure(highlightbackground="#d9d9d9")

        Entry1_1.configure(highlightcolor="black")

        Entry1_1.configure(insertbackground="black")

        Entry1_1.configure(selectbackground="blue")

        Entry1_1.configure(selectforeground="white")

        def GetFlightID():
            global pasportNO,travels,flyID
            try:
                if not pasportNO: #if the passport number is empty or wrong end
                    pass
                else:
                    flyID = Entry1_1.get()
                    cr.execute(f"SELECT FlightCode FROM Flight")
                    GList = [] #Append all the flights in a list
                    for passp0 in cr.fetchall():
                        GList.append(passp0[0])
                    if flyID in GList: #if the flight exists
                        cr.execute(f"SELECT FlightCode FROM Passenger WHERE PassportNumber={pasportNO};")
                        travels = cr.fetchall()[0][0]
                        if flyID in travels: #The Passenger Booked A Ticket In This Flight and the passenger with this passport number have ticket in this flight
                            Label5_2_1_2_1_2_1 = tk.Label(Frame1)

                            Label5_2_1_2_1_2_1.place(relx=0.06, rely=0.489, height=31, width=246)

                            Label5_2_1_2_1_2_1.configure(activebackground="#f9f9f9")

                            Label5_2_1_2_1_2_1.configure(activeforeground="black")

                            Label5_2_1_2_1_2_1.configure(background="#dcf86b")

                            Label5_2_1_2_1_2_1.configure(compound='left')

                            Label5_2_1_2_1_2_1.configure(disabledforeground="#a3a3a3")

                            Label5_2_1_2_1_2_1.configure(foreground="#000000")

                            Label5_2_1_2_1_2_1.configure(highlightbackground="#d9d9d9")

                            Label5_2_1_2_1_2_1.configure(highlightcolor="black")

                            Label5_2_1_2_1_2_1.configure(relief="solid")

                            Label5_2_1_2_1_2_1.configure(text='''The Passenger Booked A Ticket In This Flight''')

                            def Cancel_Ticket():
                                global travels,flyID
                                TRlist = travels.split(",")
                                if len(TRlist) == 1:
                                    cr.execute(f"UPDATE Passenger SET FlightCode='Null' WHERE PassportNumber={pasportNO};")
                                else:
                                    del(TRlist[TRlist.index(flyID)])
                                    OldTravel = ",".join(str(px) for px in TRlist)
                                    cr.execute(f"UPDATE Passenger SET FlightCode='{OldTravel}' WHERE PassportNumber={pasportNO};") #Checks that the passenger don't have a ticket on this flight

                                cr.execute(f"SELECT PID FROM Passenger WHERE PassportNumber={pasportNO};")
                                bid = cr.fetchall()[0][0]
                                cr.execute(f"SELECT TicketNumber FROM Ticket WHERE FlightCode='{flyID}' and PID={bid};")
                                Tnum = str(cr.fetchall()[0][0])
                                DOC1 = str(t.strftime("%d-%B-%Y")) #date of cancellition
                                
                                cr.execute(f"SELECT PID FROM Cancels")
                                Gist = [] #append all the PID in the array list
                                for pasp0 in cr.fetchall():
                                	Gist.append(pasp0[0])
                                if bid in Gist:
                                	cr.execute(f"UPDATE Cancels SET DOC='{DOC1}',TicketNumber='{Tnum}' WHERE PID= {bid}")
                                else:
                                	cr.execute(f"INSERT INTO Cancels (DOC,TicketNumber,PID) VALUES ('{DOC1}','{Tnum}',{bid})")
                                cr.execute(f"DELETE FROM Books WHERE TicketNumber='{Tnum}';")
                                cr.execute(f"DELETE FROM Ticket WHERE TicketNumber='{Tnum}';")
                                db.commit() #to save changes
                                # Cancel success message
                                Label5_2_1_2_1_2_1_1_7 = tk.Label(Frame1)
                                Label5_2_1_2_1_2_1_1_7.place(relx=0.33, rely=0.750, height=35
                                                             , width=110)
                                Label5_2_1_2_1_2_1_1_7.configure(activebackground="#f9f9f9")
                                Label5_2_1_2_1_2_1_1_7.configure(activeforeground="black")
                                Label5_2_1_2_1_2_1_1_7.configure(background="#dcf86b")
                                Label5_2_1_2_1_2_1_1_7.configure(compound='left')
                                Label5_2_1_2_1_2_1_1_7.configure(disabledforeground="#a3a3a3")
                                Label5_2_1_2_1_2_1_1_7.configure(foreground="#000000")
                                Label5_2_1_2_1_2_1_1_7.configure(highlightbackground="#d9d9d9")
                                Label5_2_1_2_1_2_1_1_7.configure(highlightcolor="black")
                                Label5_2_1_2_1_2_1_1_7.configure(relief="solid")
                                Label5_2_1_2_1_2_1_1_7.configure(text='''Cancel Success''')

                            Button1_1_1_1_1_1_1_1 = tk.Button(Frame1)

                            Button1_1_1_1_1_1_1_1.place(relx=0.806, rely=0.489, height=31, width=47)

                            Button1_1_1_1_1_1_1_1.configure(activebackground="#ececec")

                            Button1_1_1_1_1_1_1_1.configure(activeforeground="#000000")

                            Button1_1_1_1_1_1_1_1.configure(background="#70bbd1")

                            Button1_1_1_1_1_1_1_1.configure(compound='left')

                            Button1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")

                            Button1_1_1_1_1_1_1_1.configure(foreground="#000000")

                            Button1_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")

                            Button1_1_1_1_1_1_1_1.configure(highlightcolor="black")

                            Button1_1_1_1_1_1_1_1.configure(pady="0")

                            Button1_1_1_1_1_1_1_1.configure(relief="solid")

                            Button1_1_1_1_1_1_1_1.configure(text='''Cancel''')
                            Button1_1_1_1_1_1_1_1.configure(command=Cancel_Ticket)
                        else:

                            Label5_2_1_2_1_2_1_1 = tk.Label(Frame1)

                            Label5_2_1_2_1_2_1_1.place(relx=0.06, rely=0.489, height=31, width=276)

                            Label5_2_1_2_1_2_1_1.configure(activebackground="#f9f9f9")

                            Label5_2_1_2_1_2_1_1.configure(activeforeground="black")

                            Label5_2_1_2_1_2_1_1.configure(background="#dcf86b")

                            Label5_2_1_2_1_2_1_1.configure(compound='left')

                            Label5_2_1_2_1_2_1_1.configure(disabledforeground="#a3a3a3")

                            Label5_2_1_2_1_2_1_1.configure(foreground="#000000")

                            Label5_2_1_2_1_2_1_1.configure(highlightbackground="#d9d9d9")

                            Label5_2_1_2_1_2_1_1.configure(highlightcolor="black")

                            Label5_2_1_2_1_2_1_1.configure(relief="solid")

                            Label5_2_1_2_1_2_1_1.configure(text='''The Passenger Dont Have A Ticket In This Flight''')
                    else:
                        Label5_2_1_12_1_2_1 = tk.Label(Frame1)
                        Label5_2_1_12_1_2_1.place(relx=0.06, rely=0.489, height=31, width=246)
                        Label5_2_1_12_1_2_1.configure(activebackground="#f9f9f9")
                        Label5_2_1_12_1_2_1.configure(activeforeground="black")
                        Label5_2_1_12_1_2_1.configure(background="#dcf86b")
                        Label5_2_1_12_1_2_1.configure(compound='left')
                        Label5_2_1_12_1_2_1.configure(disabledforeground="#a3a3a3")
                        Label5_2_1_12_1_2_1.configure(foreground="#000000")
                        Label5_2_1_12_1_2_1.configure(highlightbackground="#d9d9d9")
                        Label5_2_1_12_1_2_1.configure(highlightcolor="black")
                        Label5_2_1_12_1_2_1.configure(relief="solid")
                        Label5_2_1_12_1_2_1.configure(text='''This Flight is not Exist You Can't Cancel A Ticket''')
            except:
                pass


        Button1_1_1_1_1_2 = tk.Button(Frame1)

        Button1_1_1_1_1_2.place(relx=0.806, rely=0.178, height=31, width=47)


        Button1_1_1_1_1_2.configure(activebackground="#ececec")

        Button1_1_1_1_1_2.configure(activeforeground="#000000")

        Button1_1_1_1_1_2.configure(background="#70bbd1")

        Button1_1_1_1_1_2.configure(compound='left')

        Button1_1_1_1_1_2.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1_2.configure(foreground="#000000")

        Button1_1_1_1_1_2.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1_2.configure(highlightcolor="black")

        Button1_1_1_1_1_2.configure(pady="0")

        Button1_1_1_1_1_2.configure(relief="solid")

        Button1_1_1_1_1_2.configure(text='''Search''')
        Button1_1_1_1_1_2.configure(command=GetFlightID)

        Frame1_1 = tk.Frame(top)

        Frame1_1.place(relx=0.5, rely=0.55, relheight=0.375, relwidth=0.494)


        Frame1_1.configure(relief='groove')

        Frame1_1.configure(borderwidth="2")

        Frame1_1.configure(relief="groove")

        Frame1_1.configure(background="#d9d9d9")

        Frame1_1.configure(cursor="fleur")

        Frame1_1.configure(highlightbackground="#d9d9d9")

        Frame1_1.configure(highlightcolor="black")


        Label5_2_1_4_1 = tk.Label(Frame1_1)

        Label5_2_1_4_1.place(relx=0.0, rely=0.0, height=31, width=346)

        Label5_2_1_4_1.configure(activebackground="#f9f9f9")

        Label5_2_1_4_1.configure(activeforeground="black")

        Label5_2_1_4_1.configure(background="#70bbd1")

        Label5_2_1_4_1.configure(compound='left')

        Label5_2_1_4_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_4_1.configure(foreground="#000000")

        Label5_2_1_4_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_4_1.configure(highlightcolor="black")

        Label5_2_1_4_1.configure(relief="solid")

        Label5_2_1_4_1.configure(text='''Book A Ticket''')


        Label5_2_1_3_1_1 = tk.Label(Frame1_1)

        Label5_2_1_3_1_1.place(relx=0.029, rely=0.178, height=31, width=107)


        Label5_2_1_3_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_3_1_1.configure(activeforeground="black")

        Label5_2_1_3_1_1.configure(background="#70bbd1")

        Label5_2_1_3_1_1.configure(compound='left')

        Label5_2_1_3_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_3_1_1.configure(foreground="#000000")

        Label5_2_1_3_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_3_1_1.configure(highlightcolor="black")

        Label5_2_1_3_1_1.configure(relief="solid")

        Label5_2_1_3_1_1.configure(text='''Enter Flight Code''')


        Entry1_1_1 = tk.Entry(Frame1_1)

        Entry1_1_1.place(relx=0.347, rely=0.178, height=31, relwidth=0.416)

        Entry1_1_1.configure(background="white")

        Entry1_1_1.configure(disabledforeground="#a3a3a3")

        Entry1_1_1.configure(font="TkFixedFont")

        Entry1_1_1.configure(foreground="#000000")

        Entry1_1_1.configure(highlightbackground="#d9d9d9")

        Entry1_1_1.configure(highlightcolor="black")

        Entry1_1_1.configure(insertbackground="black")

        Entry1_1_1.configure(selectbackground="blue")

        Entry1_1_1.configure(selectforeground="white")

        def GetFlightID2():
            global pasportNO,flyID2
            try:
                if not pasportNO:
                    pass
                else:
                    flyID2 = Entry1_1_1.get()
                    cr.execute(f"SELECT FlightCode FROM Flight")
                    MList = [] #APPEND ALL FLIGHTS IN THE LIST
                    for passp1 in cr.fetchall():
                        MList.append(passp1[0])
                    if flyID2 in MList:
                        cr.execute(f"SELECT FlightCode FROM Passenger WHERE PassportNumber={pasportNO};")
                        SDa = cr.fetchall()[0][0].split(",") #Fetchs the flight ID EX:['KU1005']
                        if flyID2 not in SDa: #This Flight Exist You Can Book A Ticket

                            Label5_2_1_2_1_2_1_2 = tk.Label(Frame1_1)

                            Label5_2_1_2_1_2_1_2.place(relx=0.029, rely=0.489, height=31

                                                       , width=246)

                            Label5_2_1_2_1_2_1_2.configure(activebackground="#f9f9f9")

                            Label5_2_1_2_1_2_1_2.configure(activeforeground="black")

                            Label5_2_1_2_1_2_1_2.configure(background="#dcf86b")

                            Label5_2_1_2_1_2_1_2.configure(compound='left')

                            Label5_2_1_2_1_2_1_2.configure(disabledforeground="#a3a3a3")

                            Label5_2_1_2_1_2_1_2.configure(foreground="#000000")

                            Label5_2_1_2_1_2_1_2.configure(highlightbackground="#d9d9d9")

                            Label5_2_1_2_1_2_1_2.configure(highlightcolor="black")

                            Label5_2_1_2_1_2_1_2.configure(relief="solid")

                            Label5_2_1_2_1_2_1_2.configure(text='''This Flight Exist You Can Book A Ticket''')

                            def Book_Ticket():
                                global flyID2,pasportNO,EmPloyId
                                cr.execute(f"SELECT PID FROM Passenger WHERE PassportNumber={pasportNO};")
                                DOB = str(t.strftime("%d-%B-%Y"))
                                RTN = str(random.choice(range(1000000,10000000)))+str(random.choice(range(100000,1000000)))
                                pid = cr.fetchall()[0][0] #fetchs the passnger ID
                                cr.execute(f"INSERT INTO books (DateOfBooking, TicketNumber,PID) VALUES ('{DOB}','{RTN}',{pid});")
                                if "Null" in SDa:
                                    cr.execute(f"UPDATE Passenger SET FlightCode='{flyID2}' WHERE PassportNumber={pasportNO};") #flyID2 = Entry1_1_1.get()

                                else:
                                    flyID0 = ",".join(str(ex)for ex in SDa)+","+flyID2 #KU1005,SP4306,TU5556
                                    cr.execute(f"UPDATE Passenger SET FlightCode='{flyID0}' WHERE PassportNumber={pasportNO};")

                                cr.execute(f"INSERT INTO Ticket (TicketNumber,FlightCode,PID,EmployeeID) VALUES ('{RTN}','{flyID2}',{pid},{EmPloyId});")
                                db.commit() #to save changes
                                # Book success message
                                Label5_2_1_2_1_2_1_1_1_8 = tk.Label(Frame1_1)
                                Label5_2_1_2_1_2_1_1_1_8.place(relx=0.30, rely=0.750, height=35,width=110)
                                Label5_2_1_2_1_2_1_1_1_8.configure(activebackground="#f9f9f9")
                                Label5_2_1_2_1_2_1_1_1_8.configure(activeforeground="black")
                                Label5_2_1_2_1_2_1_1_1_8.configure(background="#dcf86b")
                                Label5_2_1_2_1_2_1_1_1_8.configure(compound='left')
                                Label5_2_1_2_1_2_1_1_1_8.configure(disabledforeground="#a3a3a3")
                                Label5_2_1_2_1_2_1_1_1_8.configure(foreground="#000000")
                                Label5_2_1_2_1_2_1_1_1_8.configure(highlightbackground="#d9d9d9")
                                Label5_2_1_2_1_2_1_1_1_8.configure(highlightcolor="black")
                                Label5_2_1_2_1_2_1_1_1_8.configure(relief="solid")
                                Label5_2_1_2_1_2_1_1_1_8.configure(text='''Book Success''')

                            Button1_1_1_1_1_1_1_1_1 = tk.Button(Frame1_1)

                            Button1_1_1_1_1_1_1_1_1.place(relx=0.751, rely=0.489, height=31

                                                          , width=47)

                            Button1_1_1_1_1_1_1_1_1.configure(activebackground="#ececec")

                            Button1_1_1_1_1_1_1_1_1.configure(activeforeground="#000000")

                            Button1_1_1_1_1_1_1_1_1.configure(background="#70bbd1")

                            Button1_1_1_1_1_1_1_1_1.configure(compound='left')

                            Button1_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")

                            Button1_1_1_1_1_1_1_1_1.configure(foreground="#000000")

                            Button1_1_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")

                            Button1_1_1_1_1_1_1_1_1.configure(highlightcolor="black")

                            Button1_1_1_1_1_1_1_1_1.configure(pady="0")

                            Button1_1_1_1_1_1_1_1_1.configure(relief="solid")

                            Button1_1_1_1_1_1_1_1_1.configure(text='''Book''')

                            Button1_1_1_1_1_1_1_1_1.configure(command=Book_Ticket)
                        else:
                            Label5_2_1_0_1_2_1_1_1 = tk.Label(Frame1_1)
                            Label5_2_1_0_1_2_1_1_1.place(relx=0.061, rely=0.489, height=31, width=276)
                            Label5_2_1_0_1_2_1_1_1.configure(activebackground="#f9f9f9")
                            Label5_2_1_0_1_2_1_1_1.configure(activeforeground="black")
                            Label5_2_1_0_1_2_1_1_1.configure(background="#dcf86b")
                            Label5_2_1_0_1_2_1_1_1.configure(compound='left')
                            Label5_2_1_0_1_2_1_1_1.configure(disabledforeground="#a3a3a3")
                            Label5_2_1_0_1_2_1_1_1.configure(foreground="#000000")
                            Label5_2_1_0_1_2_1_1_1.configure(highlightbackground="#d9d9d9")
                            Label5_2_1_0_1_2_1_1_1.configure(highlightcolor="black")
                            Label5_2_1_0_1_2_1_1_1.configure(relief="solid")
                            Label5_2_1_0_1_2_1_1_1.configure(text='''You have already this flight ticket''')

                    else:
                        Label5_2_1_2_1_2_1_1_1 = tk.Label(Frame1_1)
                        Label5_2_1_2_1_2_1_1_1.place(relx=0.061, rely=0.489, height=31 , width=276)
                        Label5_2_1_2_1_2_1_1_1.configure(activebackground="#f9f9f9")
                        Label5_2_1_2_1_2_1_1_1.configure(activeforeground="black")
                        Label5_2_1_2_1_2_1_1_1.configure(background="#dcf86b")
                        Label5_2_1_2_1_2_1_1_1.configure(compound='left')
                        Label5_2_1_2_1_2_1_1_1.configure(disabledforeground="#a3a3a3")
                        Label5_2_1_2_1_2_1_1_1.configure(foreground="#000000")
                        Label5_2_1_2_1_2_1_1_1.configure(highlightbackground="#d9d9d9")
                        Label5_2_1_2_1_2_1_1_1.configure(highlightcolor="black")
                        Label5_2_1_2_1_2_1_1_1.configure(relief="solid")
                        Label5_2_1_2_1_2_1_1_1.configure(text='''This Flight is not Exist You Can't Book A Ticket''')
                                                         
            except:
                pass

        Button1_1_1_1_1_2_1 = tk.Button(Frame1_1)

        Button1_1_1_1_1_2_1.place(relx=0.78, rely=0.178, height=31

                , width=47)

        Button1_1_1_1_1_2_1.configure(activebackground="#ececec")

        Button1_1_1_1_1_2_1.configure(activeforeground="#000000")

        Button1_1_1_1_1_2_1.configure(background="#70bbd1")

        Button1_1_1_1_1_2_1.configure(compound='left')

        Button1_1_1_1_1_2_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1_2_1.configure(foreground="#000000")

        Button1_1_1_1_1_2_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1_2_1.configure(highlightcolor="black")

        Button1_1_1_1_1_2_1.configure(pady="0")

        Button1_1_1_1_1_2_1.configure(relief="solid")

        Button1_1_1_1_1_2_1.configure(text='''Search''')
        Button1_1_1_1_1_2_1.configure(command=GetFlightID2)

    #___________________________________
    #edit passenger information
    def Edit_Passenger_info(FirstName=None,LastName=None,Age=None,PassportNum=None,PhoneNum=None,Genderr=None):
        #this distorys the prvs window and replace it with new one (Edit Passenger Info)
        window = replace_window()
        window.geometry("700x600+679+123")
        top = window

        Label1 = tk.Label(top)

        Label1.place(relx=0.0, rely=0.0, height=58, width=700)

        Label1.configure(background="#70bbd1")

        Label1.configure(compound='left')

        Label1.configure(disabledforeground="#a3a3a3")

        Label1.configure(font="-family {Segoe UI} -size 24 -weight bold -slant italic")

        Label1.configure(foreground="#000000")

        Label1.configure(relief="solid")

        Label1.configure(text='''KU Airport Mangment System (Admin)''')

        Label2 = tk.Label(top)

        Label2.place(relx=0.471, rely=0.117, height=54, width=54)

        Label2.configure(anchor='w')

        Label2.configure(background="#d9d9d9")

        Label2.configure(compound='left')

        Label2.configure(disabledforeground="#a3a3a3")

        Label2.configure(foreground="#000000")

        photo_location = "./ezgif-5-4a4aa8b9f3.gif"

        global _img0

        _img0 = tk.PhotoImage(file=photo_location)

        Label2.configure(image=_img0)

        Label3 = tk.Label(top)

        Label3.place(relx=0.014, rely=0.217, height=31, width=686)

        Label3.configure(background="#a6a79a")

        Label3.configure(compound='left')

        Label3.configure(disabledforeground="#a3a3a3")

        Label3.configure(font="-family {Segoe UI} -size 14 -weight bold -slant italic -underline 1")

        Label3.configure(foreground="#000000")

        Label3.configure(relief="solid")

        Label3.configure(text='''Welcome To The Admin ( Edit Passenger Information )''')

        Label5_2 = tk.Label(top)

        Label5_2.place(relx=0.529, rely=0.4, height=31, width=106)

        Label5_2.configure(activebackground="#f9f9f9")

        Label5_2.configure(activeforeground="black")

        Label5_2.configure(background="#70bbd1")

        Label5_2.configure(compound='left')

        Label5_2.configure(disabledforeground="#a3a3a3")

        Label5_2.configure(foreground="#000000")

        Label5_2.configure(highlightbackground="#d9d9d9")

        Label5_2.configure(highlightcolor="black")

        Label5_2.configure(relief="solid")

        Label5_2.configure(text='''Passport Number''')

        Label5_2_1 = tk.Label(top)

        Label5_2_1.place(relx=0.043, rely=0.4, height=31, width=96)

        Label5_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1.configure(activeforeground="black")

        Label5_2_1.configure(background="#70bbd1")

        Label5_2_1.configure(compound='left')

        Label5_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1.configure(foreground="#000000")

        Label5_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1.configure(highlightcolor="black")

        Label5_2_1.configure(relief="solid")

        Label5_2_1.configure(text='''First Name''')

        Label5_2_1_1 = tk.Label(top)

        Label5_2_1_1.place(relx=0.043, rely=0.467, height=31, width=96)

        Label5_2_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_1.configure(activeforeground="black")

        Label5_2_1_1.configure(background="#70bbd1")

        Label5_2_1_1.configure(compound='left')

        Label5_2_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_1.configure(foreground="#000000")

        Label5_2_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_1.configure(highlightcolor="black")

        Label5_2_1_1.configure(relief="solid")

        Label5_2_1_1.configure(text='''Last Name''')

        Label5_2_2 = tk.Label(top)

        Label5_2_2.place(relx=0.529, rely=0.467, height=31, width=106)

        Label5_2_2.configure(activebackground="#f9f9f9")

        Label5_2_2.configure(activeforeground="black")

        Label5_2_2.configure(background="#70bbd1")

        Label5_2_2.configure(compound='left')

        Label5_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_2.configure(foreground="#000000")

        Label5_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_2.configure(highlightcolor="black")

        Label5_2_2.configure(relief="solid")

        Label5_2_2.configure(text='''Phone Number''')

        Label5_2_1_2 = tk.Label(top)

        Label5_2_1_2.place(relx=1.114, rely=0.183, height=31, width=206)

        Label5_2_1_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2.configure(activeforeground="black")

        Label5_2_1_2.configure(background="#488184")

        Label5_2_1_2.configure(compound='left')

        Label5_2_1_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2.configure(foreground="#000000")

        Label5_2_1_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2.configure(highlightcolor="black")

        Label5_2_1_2.configure(relief="solid")

        Label5_2_1_2.configure(text='''First Name''')

        Label5_2_1_2_1 = tk.Label(top)

        Label5_2_1_2_1.place(relx=0.686, rely=0.467, height=31, width=206)

        Label5_2_1_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1.configure(activeforeground="black")

        Label5_2_1_2_1.configure(background="#dcf86b")

        Label5_2_1_2_1.configure(compound='left')

        Label5_2_1_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1.configure(foreground="#000000")

        Label5_2_1_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1.configure(highlightcolor="black")

        Label5_2_1_2_1.configure(relief="solid")

        Label5_2_1_2_1.configure(text=PhoneNum)

        Label5_2_1_2_2 = tk.Label(top)

        Label5_2_1_2_2.place(relx=0.2, rely=0.467, height=31, width=206)

        Label5_2_1_2_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2.configure(activeforeground="black")

        Label5_2_1_2_2.configure(background="#dcf86b")

        Label5_2_1_2_2.configure(compound='left')

        Label5_2_1_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2.configure(foreground="#000000")

        Label5_2_1_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2.configure(highlightcolor="black")

        Label5_2_1_2_2.configure(relief="solid")

        Label5_2_1_2_2.configure(text=LastName)


        Label5_2_1_2_2_1 = tk.Label(top)

        Label5_2_1_2_2_1.place(relx=0.686, rely=0.4, height=31, width=206)

        Label5_2_1_2_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2_1.configure(activeforeground="black")

        Label5_2_1_2_2_1.configure(background="#dcf86b")

        Label5_2_1_2_2_1.configure(compound='left')

        Label5_2_1_2_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2_1.configure(foreground="#000000")

        Label5_2_1_2_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2_1.configure(highlightcolor="black")

        Label5_2_1_2_2_1.configure(relief="solid")

        Label5_2_1_2_2_1.configure(text=PassportNum)

        Label5_2_1_2_1_1 = tk.Label(top)

        Label5_2_1_2_1_1.place(relx=1.029, rely=0.183, height=31, width=206)

        Label5_2_1_2_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1_1.configure(activeforeground="black")

        Label5_2_1_2_1_1.configure(background="#2f5355")

        Label5_2_1_2_1_1.configure(compound='left')

        Label5_2_1_2_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1_1.configure(foreground="#000000")

        Label5_2_1_2_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1_1.configure(highlightcolor="black")

        Label5_2_1_2_1_1.configure(relief="solid")

        Label5_2_1_2_1_1.configure(text='''First Name''')

        Label5_2_1_2_1_2 = tk.Label(top)

        Label5_2_1_2_1_2.place(relx=0.2, rely=0.4, height=31, width=206)

        Label5_2_1_2_1_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1_2.configure(activeforeground="black")

        Label5_2_1_2_1_2.configure(background="#dcf86b")

        Label5_2_1_2_1_2.configure(compound='left')

        Label5_2_1_2_1_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1_2.configure(foreground="#000000")

        Label5_2_1_2_1_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1_2.configure(highlightcolor="black")

        Label5_2_1_2_1_2.configure(relief="solid")

        Label5_2_1_2_1_2.configure(text=FirstName)


        Button1_1_1 = tk.Button(top)

        Button1_1_1.place(relx=0.243, rely=1.567, height=44, width=77)

        Button1_1_1.configure(activebackground="#ececec")

        Button1_1_1.configure(activeforeground="#000000")

        Button1_1_1.configure(background="#970004")

        Button1_1_1.configure(compound='left')

        Button1_1_1.configure(cursor="fleur")

        Button1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1.configure(foreground="#000000")

        Button1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1.configure(highlightcolor="black")

        Button1_1_1.configure(pady="0")

        Button1_1_1.configure(relief="solid")

        Button1_1_1.configure(text='''Sign Out''')

        Entry1 = tk.Entry(top)

        Entry1.place(relx=0.4, rely=0.317, height=31, relwidth=0.249)

        Entry1.configure(background="white")

        Entry1.configure(disabledforeground="#a3a3a3")

        Entry1.configure(font="TkFixedFont")

        Entry1.configure(foreground="#000000")

        Entry1.configure(insertbackground="black")


        Label5_2_1_3 = tk.Label(top)

        Label5_2_1_3.place(relx=0.114, rely=0.317, height=31, width=187)

        Label5_2_1_3.configure(activebackground="#f9f9f9")

        Label5_2_1_3.configure(activeforeground="black")

        Label5_2_1_3.configure(background="#70bbd1")

        Label5_2_1_3.configure(compound='left')

        Label5_2_1_3.configure(disabledforeground="#a3a3a3")

        Label5_2_1_3.configure(foreground="#000000")

        Label5_2_1_3.configure(highlightbackground="#d9d9d9")

        Label5_2_1_3.configure(highlightcolor="black")

        Label5_2_1_3.configure(relief="solid")

        Label5_2_1_3.configure(text='''Enter The Passport Number''')
        #________________________________
        #Rcvs the inouts from passport# entry
        def InputText():
            #make the varable global so we can use it with its value outside this function
            global Passport_No,PData
            #rcvs the inputs and save in a variable
            Passport_No = Entry1.get()
            try:
                #fetch the passport number of all passengers from the DB
                cr.execute("SELECT PassportNumber FROM Passenger")
                #put them in a list
                SList = []
                for PassP in cr.fetchall():
                    SList.append(PassP[0])
                #check if the passport number exits
                if str(Passport_No) in SList:
                    #fetch this passenger's all info if he exists
                    cr.execute(f"SELECT Fname,Lname,Age,PassportNumber,PPhone,Sex FROM Passenger WHERE PassportNumber={Passport_No};")
                    PData = cr.fetchall()[0]
                    #put the passengers info for this passenger in the interface
                    Edit_Passenger_info(str(PData[0]),str(PData[1]),str(int(t.strftime("%Y"))-int(PData[2])),str(PData[3]),str(PData[4]),str(PData[5]))
                else:
                    #upadte it with null enrties
                    Edit_Passenger_info(None,None,None,None,None,None)
                    Passport_No = None
            except:
                Edit_Passenger_info(None,None,None,None,None,None)
        #________________________________
        #search button
        Button1_1_1_1_1 = tk.Button(top)

        Button1_1_1_1_1.place(relx=0.657, rely=0.317, height=31, width=77)

        Button1_1_1_1_1.configure(activebackground="#ececec")

        Button1_1_1_1_1.configure(activeforeground="#000000")

        Button1_1_1_1_1.configure(background="#70bbd1")

        Button1_1_1_1_1.configure(compound='left')

        Button1_1_1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1.configure(foreground="#000000")

        Button1_1_1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1.configure(highlightcolor="black")

        Button1_1_1_1_1.configure(pady="0")

        Button1_1_1_1_1.configure(relief="solid")

        Button1_1_1_1_1.configure(text='''Search''')
        
        Button1_1_1_1_1.configure(command=InputText)

        Label5_2_1_1_1 = tk.Label(top)

        Label5_2_1_1_1.place(relx=0.043, rely=0.533, height=31, width=96)

        Label5_2_1_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_1_1.configure(activeforeground="black")

        Label5_2_1_1_1.configure(background="#70bbd1")

        Label5_2_1_1_1.configure(compound='left')

        Label5_2_1_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_1_1.configure(foreground="#000000")

        Label5_2_1_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_1_1.configure(highlightcolor="black")

        Label5_2_1_1_1.configure(relief="solid")

        Label5_2_1_1_1.configure(text='''Age''')



        Label5_2_1_2_2_2 = tk.Label(top)

        Label5_2_1_2_2_2.place(relx=0.2, rely=0.533, height=31, width=206)

        Label5_2_1_2_2_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2_2.configure(activeforeground="black")

        Label5_2_1_2_2_2.configure(background="#dcf86b")

        Label5_2_1_2_2_2.configure(compound='left')

        Label5_2_1_2_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2_2.configure(foreground="#000000")

        Label5_2_1_2_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2_2.configure(highlightcolor="black")

        Label5_2_1_2_2_2.configure(relief="solid")

        Label5_2_1_2_2_2.configure(text=Age)



        Label5_2_2_1 = tk.Label(top)

        Label5_2_2_1.place(relx=0.529, rely=0.533, height=31, width=105)

        Label5_2_2_1.configure(activebackground="#f9f9f9")

        Label5_2_2_1.configure(activeforeground="black")

        Label5_2_2_1.configure(background="#70bbd1")

        Label5_2_2_1.configure(compound='left')

        Label5_2_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_2_1.configure(foreground="#000000")

        Label5_2_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_2_1.configure(highlightcolor="black")

        Label5_2_2_1.configure(relief="solid")

        Label5_2_2_1.configure(text='''Gender''')

        Button1_1_1_1_1_1 = tk.Button(top)

        Button1_1_1_1_1_1.place(relx=0.486, rely=0.933, height=31, width=97)


        Button1_1_1_1_1_1.configure(activebackground="#ececec")

        Button1_1_1_1_1_1.configure(activeforeground="#000000")

        Button1_1_1_1_1_1.configure(background="#970004")

        Button1_1_1_1_1_1.configure(compound='left')

        Button1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1_1.configure(foreground="#000000")

        Button1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1_1.configure(highlightcolor="black")

        Button1_1_1_1_1_1.configure(pady="0")

        Button1_1_1_1_1_1.configure(relief="solid")

        Button1_1_1_1_1_1.configure(text='''Sign Out''')
        Button1_1_1_1_1_1.configure(command=Destroy)


        menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)

        top.configure(menu = menubar)


        Button1_1_1_1_1_1_1 = tk.Button(top)

        Button1_1_1_1_1_1_1.place(relx=0.343, rely=0.933, height=31

                , width=97)

        Button1_1_1_1_1_1_1.configure(activebackground="#ececec")

        Button1_1_1_1_1_1_1.configure(activeforeground="#000000")

        Button1_1_1_1_1_1_1.configure(background="#70bbd1")

        Button1_1_1_1_1_1_1.configure(compound='left')

        Button1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1_1_1_1.configure(foreground="#000000")

        Button1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1_1_1_1.configure(highlightcolor="black")

        Button1_1_1_1_1_1_1.configure(pady="0")

        Button1_1_1_1_1_1_1.configure(relief="solid")

        Button1_1_1_1_1_1_1.configure(text='''Main Menu''')
        Button1_1_1_1_1_1_1.configure(command=Egal)


        Frame1 = tk.Frame(top)

        Frame1.place(relx=0.029, rely=0.6, relheight=0.325, relwidth=0.95)

        Frame1.configure(relief='groove')

        Frame1.configure(borderwidth="2")

        Frame1.configure(relief="groove")

        Frame1.configure(background="#d9d9d9")

        Label5_2_1_4 = tk.Label(Frame1)

        Label5_2_1_4.place(relx=0.03, rely=0.051, height=31, width=96)

        Label5_2_1_4.configure(activebackground="#f9f9f9")

        Label5_2_1_4.configure(activeforeground="black")

        Label5_2_1_4.configure(background="#70bbd1")

        Label5_2_1_4.configure(compound='left')

        Label5_2_1_4.configure(disabledforeground="#a3a3a3")

        Label5_2_1_4.configure(foreground="#000000")

        Label5_2_1_4.configure(highlightbackground="#d9d9d9")

        Label5_2_1_4.configure(highlightcolor="black")

        Label5_2_1_4.configure(relief="solid")

        Label5_2_1_4.configure(text='''First Name''')



        Label5_2_1_1_2 = tk.Label(Frame1)

        Label5_2_1_1_2.place(relx=0.03, rely=0.308, height=31, width=96)

        Label5_2_1_1_2.configure(activebackground="#f9f9f9")

        Label5_2_1_1_2.configure(activeforeground="black")

        Label5_2_1_1_2.configure(background="#70bbd1")

        Label5_2_1_1_2.configure(compound='left')

        Label5_2_1_1_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_1_2.configure(foreground="#000000")

        Label5_2_1_1_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_1_2.configure(highlightcolor="black")

        Label5_2_1_1_2.configure(relief="solid")

        Label5_2_1_1_2.configure(text='''Last Name''')



        Label5_2_1_1_1_1 = tk.Label(Frame1)

        Label5_2_1_1_1_1.place(relx=0.03, rely=0.564, height=31, width=96)

        Label5_2_1_1_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_1_1_1.configure(activeforeground="black")

        Label5_2_1_1_1_1.configure(background="#70bbd1")

        Label5_2_1_1_1_1.configure(compound='left')

        Label5_2_1_1_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_1_1_1.configure(foreground="#000000")

        Label5_2_1_1_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_1_1_1.configure(highlightcolor="black")

        Label5_2_1_1_1_1.configure(relief="solid")

        Label5_2_1_1_1_1.configure(text='''Age''')



        Label5_2_3 = tk.Label(Frame1)

        Label5_2_3.place(relx=0.511, rely=0.051, height=31, width=105)

        Label5_2_3.configure(activebackground="#f9f9f9")

        Label5_2_3.configure(activeforeground="black")

        Label5_2_3.configure(background="#70bbd1")

        Label5_2_3.configure(compound='left')

        Label5_2_3.configure(disabledforeground="#a3a3a3")

        Label5_2_3.configure(foreground="#000000")

        Label5_2_3.configure(highlightbackground="#d9d9d9")

        Label5_2_3.configure(highlightcolor="black")

        Label5_2_3.configure(relief="solid")

        Label5_2_3.configure(text='''Passport Number''')



        Label5_2_2_2 = tk.Label(Frame1)

        Label5_2_2_2.place(relx=0.511, rely=0.308, height=31, width=105)

        Label5_2_2_2.configure(activebackground="#f9f9f9")

        Label5_2_2_2.configure(activeforeground="black")

        Label5_2_2_2.configure(background="#70bbd1")

        Label5_2_2_2.configure(compound='left')

        Label5_2_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_2_2.configure(foreground="#000000")

        Label5_2_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_2_2.configure(highlightcolor="black")

        Label5_2_2_2.configure(relief="solid")

        Label5_2_2_2.configure(text='''Phone Number''')


        Label5_2_2_1_1 = tk.Label(Frame1)

        Label5_2_2_1_1.place(relx=0.511, rely=0.564, height=31, width=105)

        Label5_2_2_1_1.configure(activebackground="#f9f9f9")

        Label5_2_2_1_1.configure(activeforeground="black")

        Label5_2_2_1_1.configure(background="#70bbd1")

        Label5_2_2_1_1.configure(compound='left')

        Label5_2_2_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_2_1_1.configure(foreground="#000000")

        Label5_2_2_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_2_1_1.configure(highlightcolor="black")

        Label5_2_2_1_1.configure(relief="solid")

        Label5_2_2_1_1.configure(text='''Gender''')


        Entry2 = tk.Entry(Frame1)

        Entry2.place(relx=0.18, rely=0.051, height=31, relwidth=0.31)

        Entry2.configure(background="white")

        Entry2.configure(disabledforeground="#a3a3a3")

        Entry2.configure(font="TkFixedFont")

        Entry2.configure(foreground="#000000")

        Entry2.configure(insertbackground="black")


        Entry2_1 = tk.Entry(Frame1)

        Entry2_1.place(relx=0.18, rely=0.308, height=31, relwidth=0.31)

        Entry2_1.configure(background="white")

        Entry2_1.configure(disabledforeground="#a3a3a3")

        Entry2_1.configure(font="TkFixedFont")

        Entry2_1.configure(foreground="#000000")

        Entry2_1.configure(highlightbackground="#d9d9d9")

        Entry2_1.configure(highlightcolor="black")

        Entry2_1.configure(insertbackground="black")

        Entry2_1.configure(selectbackground="blue")

        Entry2_1.configure(selectforeground="white")



        Entry2_1_1 = tk.Entry(Frame1)

        Entry2_1_1.place(relx=0.18, rely=0.564, height=31, relwidth=0.31)

        Entry2_1_1.configure(background="white")

        Entry2_1_1.configure(disabledforeground="#a3a3a3")

        Entry2_1_1.configure(font="TkFixedFont")

        Entry2_1_1.configure(foreground="#000000")

        Entry2_1_1.configure(highlightbackground="#d9d9d9")

        Entry2_1_1.configure(highlightcolor="black")

        Entry2_1_1.configure(insertbackground="black")

        Entry2_1_1.configure(selectbackground="blue")

        Entry2_1_1.configure(selectforeground="white")



        Entry2_2 = tk.Entry(Frame1)

        Entry2_2.place(relx=0.677, rely=0.051, height=31, relwidth=0.31)

        Entry2_2.configure(background="white")

        Entry2_2.configure(disabledforeground="#a3a3a3")

        Entry2_2.configure(font="TkFixedFont")

        Entry2_2.configure(foreground="#000000")

        Entry2_2.configure(highlightbackground="#d9d9d9")

        Entry2_2.configure(highlightcolor="black")

        Entry2_2.configure(insertbackground="black")

        Entry2_2.configure(selectbackground="blue")

        Entry2_2.configure(selectforeground="white")



        Entry2_2_1 = tk.Entry(Frame1)

        Entry2_2_1.place(relx=0.677, rely=0.308, height=31, relwidth=0.31)

        Entry2_2_1.configure(background="white")

        Entry2_2_1.configure(disabledforeground="#a3a3a3")

        Entry2_2_1.configure(font="TkFixedFont")

        Entry2_2_1.configure(foreground="#000000")

        Entry2_2_1.configure(highlightbackground="#d9d9d9")

        Entry2_2_1.configure(highlightcolor="black")

        Entry2_2_1.configure(insertbackground="black")

        Entry2_2_1.configure(selectbackground="blue")

        Entry2_2_1.configure(selectforeground="white")



        Entry2_2_1_1 = tk.Entry(Frame1)

        Entry2_2_1_1.place(relx=0.677, rely=0.564, height=31, relwidth=0.31)



        Entry2_2_1_1.configure(background="white")

        Entry2_2_1_1.configure(disabledforeground="#a3a3a3")

        Entry2_2_1_1.configure(font="TkFixedFont")

        Entry2_2_1_1.configure(foreground="#000000")

        Entry2_2_1_1.configure(highlightbackground="#d9d9d9")

        Entry2_2_1_1.configure(highlightcolor="black")

        Entry2_2_1_1.configure(insertbackground="black")

        Entry2_2_1_1.configure(selectbackground="blue")

        Entry2_2_1_1.configure(selectforeground="white")


        Label5_2_1_2_1_3 = tk.Label(top)

        Label5_2_1_2_1_3.place(relx=0.686, rely=0.533, height=31, width=206)


        Label5_2_1_2_1_3.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1_3.configure(activeforeground="black")

        Label5_2_1_2_1_3.configure(background="#dcf86b")

        Label5_2_1_2_1_3.configure(compound='left')

        Label5_2_1_2_1_3.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1_3.configure(foreground="#000000")

        Label5_2_1_2_1_3.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1_3.configure(highlightcolor="black")

        Label5_2_1_2_1_3.configure(relief="solid")

        Label5_2_1_2_1_3.configure(text=Genderr)
        #_______________________________________
        def takeInput ():
            #  Values of input fields
            FIRSTNAME= Entry2.get()
            LASTNAME= Entry2_1.get()
            AGE0 = Entry2_1_1.get()
            if not AGE0:
                AGE = None
            else:
                #extract the year from the birth year
                AGE = int(t.strftime('%Y'))-int(AGE0)

            PASSNUM = Entry2_2.get()
            PHONENUMBER = Entry2_2_1.get()
            GENDER = Entry2_2_1_1.get()
            #filtring to select the changer that the employee done
            #___________________________
            #Here we have arranged the input values in a matrix. It is noted that if we do not enter any data, then the values of the variables will be equal to none
            AllValue = [FIRSTNAME,LASTNAME,AGE,PASSNUM,PHONENUMBER,GENDER]
            # An empty array to determine what is the index number of the fields whose values are entered
            FullValue = []
            count = 0
            for Value in AllValue :
                if Value:
                    FullValue.append(count)
                else:
                    pass

                count += 1
            #If there are no fields entered by the user, we ignore the modification, because there is a possibility that the employee will click on the update without
            # making any modifications, and in order not to implement the modification process in vain, otherwise we will implement it
            if len(FullValue) != 0 :
                
                try:
                    global Passport_No,PData
                    Passport_No = str(Passport_No)
                    if Passport_No == None:
                        pass
                    else:

                        # These are the columns of the passenger table in the database to determine which one you will use in the modification process, through the index number that we specified earlier
                        dbCoulm = ["Fname","Lname","Age","PassportNumber","PPhone","Sex"]
                        ## These quotation marks will be used if the input is text and not used if the input is non-text like age
                        Tanses = ["'","'","","","","'"]
                        #Here we are trying to be the order of updating the database with the required inputs only
                        dbQuery = "UPDATE Passenger SET "
                        for val in FullValue :
                            dbQuery += dbCoulm[val]
                            dbQuery += "="
                            dbQuery += Tanses[val]
                            dbQuery += str(AllValue[val])
                            dbQuery += Tanses[val]
                            dbQuery += ","

                        dbQuery = dbQuery[0:-1]
                        dbQuery += " WHERE PassportNumber="
                        dbQuery += Passport_No
                        try:
                            ## After completing the formulation of the order, we will execute it on the database for the update process
                            cr.execute(f"{dbQuery};")
                            db.commit()
                            ## The names not entered for the update are fetched the previous data from the global to complete the data to display after the update so that the update data alone does not appear in the interface
                            if not FIRSTNAME:
                                FIRSTNAME = PData[0]
                            if not LASTNAME:
                                LASTNAME = PData[1]
                            if not AGE0:
                                AGE0 = int(t.strftime("%Y"))-int(PData[2])
                            if not PASSNUM:
                                PASSNUM = PData[3]
                            if not PHONENUMBER:
                                PHONENUMBER = PData[4]
                            if not GENDER:
                                GENDER = PData[5]

                        # Finally display it after modification to the new interface Edit_Passenger_info(str(FIRSTNAME),str(LASTNAME),str(AGE0),str(PASSNUM),str(PHONENUMBER),str(GENDER))
                        except:
                            pass
                except:
                    pass
            else: 
                pass
            
            #___________________________


        Button1_1_1_1 = tk.Button(Frame1)

        Button1_1_1_1.place(relx=0.421, rely=0.821, height=24, width=67)

        Button1_1_1_1.configure(activebackground="#ececec")

        Button1_1_1_1.configure(activeforeground="#000000")

        Button1_1_1_1.configure(background="#70bbd1")

        Button1_1_1_1.configure(compound='left')

        Button1_1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1_1.configure(foreground="#000000")

        Button1_1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1_1.configure(highlightcolor="black")

        Button1_1_1_1.configure(pady="0")

        Button1_1_1_1.configure(relief="solid")

        Button1_1_1_1.configure(text='''Update''')
        Button1_1_1_1.configure(command=takeInput)

    #_____________________________________
    #this interface opened when login success to employee
    def EmployeeInterface(EmpData):
        
        window = replace_window()
        window.geometry("700x600+679+123")
        top = window
        #Employee information
        #====================
        DATA = EmpData[0]
        salary = DATA[0]
        lname = DATA[1]
        jobtype = DATA[2]
        fname = DATA[3]
        age = DATA[4]
        airport_name = DATA[5]
        employee_id = DATA[6]
        sex = DATA[7]
        ephone = DATA[8]
        #====================
        Label1 = tk.Label(top)

        Label1.place(relx=0.0, rely=0.0, height=58, width=700)

        Label1.configure(background="#70bbd1")

        Label1.configure(compound='left')

        Label1.configure(disabledforeground="#a3a3a3")

        Label1.configure(font="-family {Segoe UI} -size 24 -weight bold -slant italic")

        Label1.configure(foreground="#000000")

        Label1.configure(relief="solid")

        Label1.configure(text='''KU Airport Mangment System (Admin)''')

        Label2 = tk.Label(top)

        Label2.place(relx=0.471, rely=0.117, height=54, width=54)

        Label2.configure(anchor='w')

        Label2.configure(background="#d9d9d9")

        Label2.configure(compound='left')

        Label2.configure(disabledforeground="#a3a3a3")

        Label2.configure(foreground="#000000")

        photo_location = "./ezgif-5-4a4aa8b9f3.gif"

        global _img0

        _img0 = tk.PhotoImage(file=photo_location)

        Label2.configure(image=_img0)

        Label3 = tk.Label(top)

        Label3.place(relx=0.014, rely=0.217, height=31, width=686)

        Label3.configure(background="#a6a79a")

        Label3.configure(compound='left')

        Label3.configure(disabledforeground="#a3a3a3")

        Label3.configure(font="-family {Segoe UI} -size 14 -weight bold -slant italic -underline 1")

        Label3.configure(foreground="#000000")

        Label3.configure(relief="solid")

        Label3.configure(text='''Welcome To The Admin''')

        Label5_2 = tk.Label(top)

        Label5_2.place(relx=0.043, rely=0.367, height=31, width=95)

        Label5_2.configure(activebackground="#f9f9f9")

        Label5_2.configure(activeforeground="black")

        Label5_2.configure(background="#70bbd1")

        Label5_2.configure(compound='left')

        Label5_2.configure(disabledforeground="#a3a3a3")

        Label5_2.configure(foreground="#000000")

        Label5_2.configure(highlightbackground="#d9d9d9")

        Label5_2.configure(highlightcolor="black")

        Label5_2.configure(relief="solid")

        Label5_2.configure(text='''Employee ID''')

        Label5_2_1 = tk.Label(top)

        Label5_2_1.place(relx=0.043, rely=0.283, height=31, width=96)

        Label5_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1.configure(activeforeground="black")

        Label5_2_1.configure(background="#70bbd1")

        Label5_2_1.configure(compound='left')

        Label5_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1.configure(foreground="#000000")

        Label5_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1.configure(highlightcolor="black")

        Label5_2_1.configure(relief="solid")

        Label5_2_1.configure(text='''First Name''')

        Label5_2_1_1 = tk.Label(top)

        Label5_2_1_1.place(relx=0.514, rely=0.283, height=31, width=96)

        Label5_2_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_1.configure(activeforeground="black")

        Label5_2_1_1.configure(background="#70bbd1")

        Label5_2_1_1.configure(compound='left')

        Label5_2_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_1.configure(foreground="#000000")

        Label5_2_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_1.configure(highlightcolor="black")

        Label5_2_1_1.configure(relief="solid")

        Label5_2_1_1.configure(text='''Last Name''')

        Label5_2_2 = tk.Label(top)

        Label5_2_2.place(relx=0.514, rely=0.367, height=31, width=96)

        Label5_2_2.configure(activebackground="#f9f9f9")

        Label5_2_2.configure(activeforeground="black")

        Label5_2_2.configure(background="#70bbd1")

        Label5_2_2.configure(compound='left')

        Label5_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_2.configure(foreground="#000000")

        Label5_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_2.configure(highlightcolor="black")

        Label5_2_2.configure(relief="solid")

        Label5_2_2.configure(text='''Salary''')

        Label5_2_1_2 = tk.Label(top)

        Label5_2_1_2.place(relx=1.114, rely=0.183, height=31, width=206)

        Label5_2_1_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2.configure(activeforeground="black")

        Label5_2_1_2.configure(background="#488184")

        Label5_2_1_2.configure(compound='left')

        Label5_2_1_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2.configure(foreground="#000000")

        Label5_2_1_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2.configure(highlightcolor="black")

        Label5_2_1_2.configure(relief="solid")

        Label5_2_1_2.configure(text='''First Name''')

        Label5_2_1_2_1 = tk.Label(top)

        Label5_2_1_2_1.place(relx=0.2, rely=0.367, height=31, width=206)

        Label5_2_1_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1.configure(activeforeground="black")

        Label5_2_1_2_1.configure(background="#dcf86b")

        Label5_2_1_2_1.configure(compound='left')

        Label5_2_1_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1.configure(foreground="#000000")

        Label5_2_1_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1.configure(highlightcolor="black")

        Label5_2_1_2_1.configure(relief="solid")

        Label5_2_1_2_1.configure(text=employee_id) #Replaceing The EmpID empty Label with his ID fetched from the DB

        Label5_2_1_2_2 = tk.Label(top)

        Label5_2_1_2_2.place(relx=0.657, rely=0.283, height=31, width=206)

        Label5_2_1_2_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2.configure(activeforeground="black")

        Label5_2_1_2_2.configure(background="#dcf86b")

        Label5_2_1_2_2.configure(compound='left')

        Label5_2_1_2_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2.configure(foreground="#000000")

        Label5_2_1_2_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2.configure(highlightcolor="black")

        Label5_2_1_2_2.configure(relief="solid")

        Label5_2_1_2_2.configure(text=lname) #Replaceing The lastname of employee empty Label with his lname fetched from the DB

        Label5_2_1_2_2_1 = tk.Label(top)

        Label5_2_1_2_2_1.place(relx=0.657, rely=0.367, height=31, width=206)

        Label5_2_1_2_2_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_2_1.configure(activeforeground="black")

        Label5_2_1_2_2_1.configure(background="#dcf86b")

        Label5_2_1_2_2_1.configure(compound='left')

        Label5_2_1_2_2_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_2_1.configure(foreground="#000000")

        Label5_2_1_2_2_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_2_1.configure(highlightcolor="black")

        Label5_2_1_2_2_1.configure(relief="solid")

        Label5_2_1_2_2_1.configure(text=salary) #Replaceing The salary of employee empty Label with his salary fetched from the DB


        Label5_2_1_2_1_1 = tk.Label(top)

        Label5_2_1_2_1_1.place(relx=1.029, rely=0.183, height=31, width=206)


        Label5_2_1_2_1_1.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1_1.configure(activeforeground="black")

        Label5_2_1_2_1_1.configure(background="#2f5355")

        Label5_2_1_2_1_1.configure(compound='left')

        Label5_2_1_2_1_1.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1_1.configure(foreground="#000000")

        Label5_2_1_2_1_1.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1_1.configure(highlightcolor="black")

        Label5_2_1_2_1_1.configure(relief="solid")

        Label5_2_1_2_1_1.configure(text='''First Name''')


        Label5_2_1_2_1_2 = tk.Label(top)

        Label5_2_1_2_1_2.place(relx=0.2, rely=0.283, height=31, width=206)

        Label5_2_1_2_1_2.configure(activebackground="#f9f9f9")

        Label5_2_1_2_1_2.configure(activeforeground="black")

        Label5_2_1_2_1_2.configure(background="#dcf86b")

        Label5_2_1_2_1_2.configure(compound='left')

        Label5_2_1_2_1_2.configure(disabledforeground="#a3a3a3")

        Label5_2_1_2_1_2.configure(foreground="#000000")

        Label5_2_1_2_1_2.configure(highlightbackground="#d9d9d9")

        Label5_2_1_2_1_2.configure(highlightcolor="black")

        Label5_2_1_2_1_2.configure(relief="solid")

        Label5_2_1_2_1_2.configure(text=fname) #Replaceing The firstname of employee empty Label with his fname fetched from the DB


        Frame1 = tk.Frame(top)

        Frame1.place(relx=0.043, rely=0.467, relheight=0.392

                , relwidth=0.909)

        Frame1.configure(relief='groove')

        Frame1.configure(borderwidth="2")

        Frame1.configure(relief="groove")

        Frame1.configure(background="#d9d9d9")


        Label4 = tk.Label(Frame1)

        Label4.place(relx=0.0, rely=0.0, height=41, width=635)

        Label4.configure(background="#94cbcf")

        Label4.configure(compound='left')

        Label4.configure(disabledforeground="#a3a3a3")

        Label4.configure(font="-family {Segoe UI} -size 14 -weight bold -slant italic")

        Label4.configure(foreground="#000000")

        Label4.configure(relief="solid")

        Label4.configure(text='''Admin Menu''')


        Button1 = tk.Button(Frame1)

        Button1.place(relx=0.267, rely=0.34, height=44, width=277)

        Button1.configure(activebackground="#ececec")

        Button1.configure(activeforeground="#000000")

        Button1.configure(background="#dcf86b")

        Button1.configure(compound='left')

        Button1.configure(disabledforeground="#a3a3a3")

        Button1.configure(foreground="#000000")

        Button1.configure(highlightbackground="#d9d9d9")

        Button1.configure(highlightcolor="black")

        Button1.configure(pady="0")

        Button1.configure(relief="solid")

        Button1.configure(text='''Book / Cancel Ticket''')
        Button1.configure(command=Book_and_Cansel) #first option on the main menu of the employee to book/cancel ticket


        Button1_1 = tk.Button(Frame1)

        Button1_1.place(relx=0.267, rely=0.596, height=44, width=277)

        Button1_1.configure(activebackground="#ececec")

        Button1_1.configure(activeforeground="#000000")

        Button1_1.configure(background="#dcf86b")

        Button1_1.configure(compound='left')

        Button1_1.configure(disabledforeground="#a3a3a3")

        Button1_1.configure(foreground="#000000")

        Button1_1.configure(highlightbackground="#d9d9d9")

        Button1_1.configure(highlightcolor="black")

        Button1_1.configure(pady="0")

        Button1_1.configure(relief="solid")

        Button1_1.configure(text='''Edit Passenger Information''')
        Button1_1.configure(command=Edit_Passenger_info)

        Button1_1_1 = tk.Button(top)

        Button1_1_1.place(relx=0.429, rely=0.9, height=44, width=77)

        Button1_1_1.configure(activebackground="#ececec")

        Button1_1_1.configure(activeforeground="#000000")

        Button1_1_1.configure(background="#70bbd1")

        Button1_1_1.configure(compound='left')

        Button1_1_1.configure(cursor="")

        Button1_1_1.configure(disabledforeground="#a3a3a3")

        Button1_1_1.configure(foreground="#000000")

        Button1_1_1.configure(highlightbackground="#d9d9d9")

        Button1_1_1.configure(highlightcolor="black")

        Button1_1_1.configure(pady="0")

        Button1_1_1.configure(relief="solid")

        Button1_1_1.configure(text='''Sign Out''')
        Button1_1_1.configure(command=Destroy)
    	
    #__________________________________
    #login function
    def LOGIN():
        
        Label1 = tk.Label(top)
        Label1.place(relx=0.0, rely=0.0, height=58, width=700)
        Label1.configure(background="#70bbd1")
        Label1.configure(compound='left')
        Label1.configure(disabledforeground="#a3a3a3")
        Label1.configure(font="-family {Segoe UI} -size 24 -weight bold -slant italic")
        Label1.configure(foreground="#000000")
        Label1.configure(relief="solid")
        Label1.configure(text='''KU Airport Mangment System (Admin)''')

        Label2 = tk.Label(top)
        Label2.place(relx=0.471, rely=0.117, height=54, width=54)
        Label2.configure(anchor='w')
        Label2.configure(background="#d9d9d9")
        Label2.configure(compound='left')
        Label2.configure(disabledforeground="#a3a3a3")
        Label2.configure(foreground="#000000")
        photo_location = "./ezgif-5-4a4aa8b9f3.gif"
        
        _img0 = tk.PhotoImage(file=photo_location)
        Label2.configure(image=_img0)

        Frame1 = tk.Frame(top)
        Frame1.place(relx=0.171, rely=0.35, relheight=0.475, relwidth=0.65)
        Frame1.configure(relief='groove')
        Frame1.configure(borderwidth="2")
        Frame1.configure(relief="groove")
        Frame1.configure(background="#d9d9d9")

        Label4 = tk.Label(Frame1)
        Label4.place(relx=0.0, rely=0.0, height=41, width=454)
        Label4.configure(background="#70bbd1")
        Label4.configure(compound='left')
        Label4.configure(disabledforeground="#a3a3a3")
        Label4.configure(font="-family {Segoe UI} -size 18 -weight bold -slant italic")
        Label4.configure(foreground="#000000")
        Label4.configure(relief="solid")
        Label4.configure(text='''Log In''')
        
        Label5 = tk.Label(Frame1)
        Label5.place(relx=0.132, rely=0.351, height=31, width=74)
        Label5.configure(background="#70bbd1")
        Label5.configure(compound='left')
        Label5.configure(disabledforeground="#a3a3a3")
        Label5.configure(foreground="#000000")
        Label5.configure(relief="solid")
        Label5.configure(text='''Employee ID''')

        Entry1 = tk.Entry(Frame1)
        Entry1.place(relx=0.352, rely=0.351, height=31, relwidth=0.47)
        Entry1.configure(background="white")
        Entry1.configure(disabledforeground="#a3a3a3")
        Entry1.configure(font="TkFixedFont")
        Entry1.configure(foreground="#000000")
        Entry1.configure(insertbackground="black")

        Label5_1 = tk.Label(Frame1)
        Label5_1.place(relx=0.187, rely=1.449, height=31, width=74)
        Label5_1.configure(activebackground="#f9f9f9")
        Label5_1.configure(activeforeground="black")
        Label5_1.configure(anchor='w')
        Label5_1.configure(background="#70bbd1")
        Label5_1.configure(compound='left')
        Label5_1.configure(disabledforeground="#a3a3a3")
        Label5_1.configure(foreground="#000000")
        Label5_1.configure(highlightbackground="#d9d9d9")
        Label5_1.configure(highlightcolor="black")
        Label5_1.configure(relief="solid")
        Label5_1.configure(text='''Employee ID''')

        Entry1_1 = tk.Entry(Frame1,show="*")
        Entry1_1.place(relx=0.352, rely=0.561, height=31, relwidth=0.47)
        Entry1_1.configure(background="white")
        Entry1_1.configure(disabledforeground="#a3a3a3")
        Entry1_1.configure(font="TkFixedFont")
        Entry1_1.configure(foreground="#000000")
        Entry1_1.configure(highlightbackground="#d9d9d9")
        Entry1_1.configure(highlightcolor="black")
        Entry1_1.configure(insertbackground="black")
        Entry1_1.configure(selectbackground="blue")
        Entry1_1.configure(selectforeground="white")
        		
        Label3 = tk.Label(top)
        Label3.place(relx=0.014, rely=0.217, height=31, width=686)
        Label3.configure(background="#a6a79a")
        Label3.configure(compound='left')
        Label3.configure(disabledforeground="#a3a3a3")
        Label3.configure(font="-family {Segoe UI} -size 14 -weight bold -slant italic -underline 1")
        Label3.configure(foreground="#000000")
        Label3.configure(relief="solid")
        Label3.configure(text='''Welcome To The Admin, Please Log In With Your Employee ID and Password''')

        Label5_2 = tk.Label(top)
        Label5_2.place(relx=0.257, rely=0.617, height=31, width=75)
        Label5_2.configure(activebackground="#f9f9f9")
        Label5_2.configure(activeforeground="black")
        Label5_2.configure(background="#70bbd1")
        Label5_2.configure(compound='left')
        Label5_2.configure(disabledforeground="#a3a3a3")
        Label5_2.configure(foreground="#000000")
        Label5_2.configure(highlightbackground="#d9d9d9")
        Label5_2.configure(highlightcolor="black")
        Label5_2.configure(relief="solid")
        Label5_2.configure(text='''Password''')
        
        #________________________________
        def InputText():
            global EmPloyId
            employeeID = Entry1.get()
            UserPass = Entry1_1.get()

            try:
                cr.execute(f"SELECT Password FROM Employee WHERE EmployeeID={employeeID};")
                RealPass = cr.fetchall()[0][0]
                if RealPass == UserPass:
                    EmPloyId = employeeID
                    cr.execute(
                        f"SELECT Salary,Lname,JobType,Fname,Age,AirPortName,EmployeeID,Sex,EPhone FROM Employee WHERE EmployeeID={employeeID};")
                    EmpDeta = cr.fetchall()
                    EmployeeInterface(EmpDeta)
                else:
                    LoginFailMessage()
            except:
                LoginFailMessage()
        #________________________________
        
        Button1 = tk.Button(Frame1)
        Button1.place(relx=0.396, rely=0.807, height=34, width=77)
        Button1.configure(activebackground="#ececec")
        Button1.configure(activeforeground="#000000")
        Button1.configure(background="#d9d9d9")
        Button1.configure(compound='left')
        Button1.configure(disabledforeground="#a3a3a3")
        Button1.configure(foreground="#000000")
        Button1.configure(highlightbackground="#d9d9d9")
        Button1.configure(highlightcolor="black")
        Button1.configure(pady="0")
        Button1.configure(text='''Login''')
        Button1.configure(command=InputText)
        
        #exit function
        Button01 = tk.Button(top)
        Button01.place(relx=0.429, rely=0.9, height=44, width=77)
        Button01.configure(activebackground="#ececec")
        Button01.configure(activeforeground="#000000")
        Button01.configure(background="#d9d9d9")
        Button01.configure(compound='left')
        Button01.configure(disabledforeground="#a3a3a3")
        Button01.configure(foreground="#000000")
        Button01.configure(highlightbackground="#d9d9d9")
        Button01.configure(highlightcolor="black")
        Button01.configure(pady="0")
        Button01.configure(text="""Exit""")
        Button01.configure(command=root.destroy)
        
        

    LOGIN()
        
if __name__ == '__main__':
    main()
    root.mainloop()
    db.close()